//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticuloMedida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArticuloMedida()
        {
            this.ArticuloMedidaPosicion = new HashSet<ArticuloMedidaPosicion>();
            this.Movimiento = new HashSet<Movimiento>();
            this.ProveedorArticulo = new HashSet<ProveedorArticulo>();
            this.VentaArticulo = new HashSet<VentaArticulo>();
        }
    
        public int IdArticuloMedida { get; set; }
        public int IdMedida { get; set; }
        public int IdArticulo { get; set; }
        public Nullable<int> CantidadMinima { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Medida Medida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticuloMedidaPosicion> ArticuloMedidaPosicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento> Movimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProveedorArticulo> ProveedorArticulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VentaArticulo> VentaArticulo { get; set; }
    }
}
