//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticuloMedidaPosicion
    {
        public int IdArticuloMedidaPosicion { get; set; }
        public int IdArticuloMedida { get; set; }
        public int IdPosicion { get; set; }
        public int Cantidad { get; set; }
    
        public virtual ArticuloMedida ArticuloMedida { get; set; }
        public virtual Posicion Posicion { get; set; }
    }
}
