//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticuloCategoria
    {
        public int IdArticuloCategoria { get; set; }
        public int IdArticulo { get; set; }
        public int IdCategoria { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual Catergoria Catergoria { get; set; }
    }
}
