//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaRelacion
    {
        public int IdCategoriaRelacion { get; set; }
        public int IdCategoriaPadre { get; set; }
        public int IdCategoriaHijo { get; set; }
    
        public virtual Catergoria Catergoria { get; set; }
        public virtual Catergoria Catergoria1 { get; set; }
    }
}
