//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public int IdMovimiento { get; set; }
        public int IdTipoMovimiento { get; set; }
        public int IdArticuloMedida { get; set; }
        public Nullable<int> IdPosicionOrigen { get; set; }
        public Nullable<int> IdProveedorOrigen { get; set; }
        public Nullable<int> IdVentaOrigen { get; set; }
        public Nullable<int> IdPosicionDestino { get; set; }
        public Nullable<int> IdProveedorDestino { get; set; }
        public Nullable<int> IdVentaDestino { get; set; }
        public int Cantidad { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual ArticuloMedida ArticuloMedida { get; set; }
        public virtual Posicion Posicion { get; set; }
        public virtual Posicion Posicion1 { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Proveedor Proveedor1 { get; set; }
        public virtual TipoMovimiento TipoMovimiento { get; set; }
        public virtual Venta Venta { get; set; }
        public virtual Venta Venta1 { get; set; }
    }
}
