//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProveedorArticulo
    {
        public int IdProveedorArticulo { get; set; }
        public int IdProveedor { get; set; }
        public int IdArticuloMedida { get; set; }
        public int IdForma { get; set; }
        public decimal Precio { get; set; }
        public int Cantidad { get; set; }
        public Nullable<System.DateTime> FechaCompra { get; set; }
        public Nullable<System.DateTime> FechaPedido { get; set; }
        public Nullable<bool> Entregado { get; set; }
        public Nullable<int> PlazoPactado { get; set; }
    
        public virtual ArticuloMedida ArticuloMedida { get; set; }
        public virtual FormaPago FormaPago { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
